/*using System;
using System.Linq;
using System.Collections.Generic;

namespace Exep
{
    public class Exeption 
    { 
    	static void Main()
    	{
        int x1,x2,res;
        res = x1 = x2 = 0;
        
        x1 = 10;
        x2 = 0;
        
        try{
        	res = x1/x2;
        	Console.WriteLine($"Divisão Concluida: {x1}/{x2} = {res}");
        }catch(DivideByZeroException e){
        	Console.WriteLine($"Erro {e.Message}\n");
        	Console.WriteLine($"Ex: {e.GetType()}");
        }
    	}
    }
}*/